name: acl
version: 2.2.52
epoch: 2
sources:
  - href: "http://download.savannah.nongnu.org/releases/acl/acl-2.2.52.src.tar.gz"
    verification:
      type: sha256
      sum: 179074bb0580c06c4b4137be4c5a92a701583277967acdb5546043c7874e0d23
depends:
  build:
    - tar
    - gzip
    - make
scripts:
  install:
    - tar xf "$srcdir/acl-$version.src.tar.gz"
    - cd "acl-$version"
    - ./configure --prefix=/usr
    - make "DESTDIR=$pkgdir" install install-lib
