name: gettext
version: 0.19.8.1
depends:
  build:
    - tar
    - xz
sources:
  - href: "http://ftp.gnu.org/pub/gnu/gettext/gettext-0.19.8.1.tar.xz"
    verification:
      type: sha256
      sum: 105556dbc5c3fbbc2aa0edb46d22d055748b6f5c7cd7a8d99f8e7eb84e938be4
scripts:
  install:
    - tar xf "$srcdir/gettext-$version.tar.xz"
    - cd "gettext-$version"
    - ./configure
    - make DESTDIR="$pkgdir" install
