name: grep
version: 3.1
depends:
  all:
    - pcre
  build:
    - tar
    - xz
sources:
  - href: "https://ftpmirror.gnu.org/grep/grep-3.1.tar.xz"
    verification:
      type: sha256
      sum: db625c7ab3bb3ee757b3926a5cfa8d9e1c3991ad24707a83dde8a5ef2bf7a07e
scripts:
  install:
    - tar xf "$srcdir/grep-$version.tar.xz"
    - cd "grep-$version"
    - ./configure --prefix=/usr
    - make "DESTDIR=$pkgdir" install
