name: attr
version: 2.4.47
sources:
  - href: http://download.savannah.nongnu.org/releases/attr/attr-2.4.47.src.tar.gz
    verification:
      type: sha256
      sum: 25772f653ac5b2e3ceeb89df50e4688891e21f723c460636548971652af0a859
depends:
  build:
    - tar
    - gzip
scripts:
  install:
    - tar xf "$srcdir/attr-$version.src.tar.gz"
    - cd "attr-$version"
    - ./configure
    - make "DESTDIR=$pkgdir" install install-lib
