name: make
version: 4.2.1
depends:
  all:
    - glibc
  build:
    - make
    - bzip2
    - tar
sources:
  - href: "http://ftp.gnu.org/gnu/make/make-4.2.1.tar.bz2"
    verification:
      type: sha256
      sum: d6e262bf3601b42d2b1e4ef8310029e1dcf20083c5446b4b7aa67081fdffc589
scripts:
  install:
    - tar xf "$srcdir/make-$version.tar.bz2"
    - cd "make-$version"
    - ./configure
    - make DESTDIR="$pkgdir" install
