name: fish
version: 2.7.1
depends:
  all:
    - curses
    - gettext
    - glibc
  build:
    - cc
    - make
    - tar
    - gzip
sources:
  - href: "https://github.com/fish-shell/fish-shell/releases/download/2.7.1/fish-2.7.1.tar.gz"
    verification:
      type: sha256
      sum: e42bb19c7586356905a58578190be792df960fa81de35effb1ca5a5a981f0c5a
scripts:
  install:
    - tar xf "$srcdir/fish-$version.tar.gz"
    - cd "fish-$version"
    - ./configure
    - make "DESTDIR=$pkgdir" install
